name: Development Builds

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-dev:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Get short SHA
      id: vars
      shell: bash
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Windows (Development)
      run: |
        dotnet publish `
          --configuration Release `
          --runtime win-x64 `
          --self-contained true `
          --output ./dev-builds/windows `
          -p:PublishSingleFile=true `
          -p:PublishTrimmed=true `
          -p:TrimMode=partial

    - name: Create development archive
      run: |
        Compress-Archive -Path ./dev-builds/windows/* -DestinationPath ./dev-builds/noita-savescummer-dev-windows-${{ steps.vars.outputs.sha_short }}.zip

    - name: Upload development builds
      uses: actions/upload-artifact@v4
      with:
        name: development-builds-${{ steps.vars.outputs.sha_short }}
        path: |
          ./dev-builds/*.zip
        retention-days: 30

    - name: Create or update development release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: dev-latest
        name: "🚧 Development Build (Latest)"
        body: |
          # 🚧 Development Build - Latest Commit
          
          **⚠️ Development Build Warning**
          This is an automatic build from the latest code. It may be unstable!
          
          **Commit:** ${{ github.sha }}
          **Short SHA:** ${{ steps.vars.outputs.sha_short }}
          **Built:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC")
          
          ## Download
          
          - `noita-savescummer-dev-windows-${{ steps.vars.outputs.sha_short }}.zip` - Windows 10/11 (64-bit)
          
          **Requirements:** Windows 10/11, Noita installed
          
          ---
          *For stable releases, check the main releases page*
        draft: false
        prerelease: true
        files: |
          ./dev-builds/noita-savescummer-dev-windows-${{ steps.vars.outputs.sha_short }}.zip
